services:
  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: ${DEFAULT_DATABASE_PASSWORD}
      POSTGRES_USER: ${DEFAULT_DATABASE_USER}
      POSTGRES_DB: ${DEFAULT_DATABASE_NAME}
      COMPOSE_HTTP_TIMEOUT: 300
    ports:
      - 5432:5432
    volumes:
      - postgresdata:/var/lib/postgresql/data
  adminer:
    image: adminer
    ports:
      - ${PG_ADMIN_PORT}:8080
volumes:
  postgresdata:
