services:
  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: ${DEFAULT_DATABASE_PASSWORD}
      POSTGRES_USER: ${DEFAULT_DATABASE_USER}
      POSTGRES_DB: ${DEFAULT_DATABASE_NAME}
    ports:
      - 5432:5432
    volumes:
      - postgresdata:/var/lib/postgresql/data
  adminer:
    image: adminer
    ports:
      - 8081:8080
  foosrefmanagement:
    image: nkuznetsov44/foosrefmanagement
    build:
      context: ./foosrefmanagement
      dockerfile: Dockerfile
    depends_on:
      - postgres
    environment:
      ENVIRONMENT: "DOCKER"
      DEFAULT_DATABASE_NAME: ${DEFAULT_DATABASE_NAME}
      DEFAULT_DATABASE_USER: ${DEFAULT_DATABASE_USER}
      DEFAULT_DATABASE_PASSWORD: ${DEFAULT_DATABASE_PASSWORD}
      DEFAULT_DATABASE_HOST: postgres
      DEFAULT_DATABASE_PORT: 5432
      DJANGO_SUPERUSER_TELEGRAM_ID: ${DJANGO_SUPERUSER_TELEGRAM_ID}
      DJANGO_SUPERUSER_PASSWORD: ${DJANGO_SUPERUSER_PASSWORD}
      TELEGRAM_BOT_API_TOKEN: ${TELEGRAM_BOT_API_TOKEN}
      DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY}
      APP_EXTERNAL_HOST: ${APP_EXTERNAL_HOST}
      DJANGO_ALLOWED_HOSTS: ${DJANGO_ALLOWED_HOSTS}
    volumes:
      - staticfiles:/usr/src/app/staticfiles
      - media:/usr/src/app/media
  nginx:
    build:
      context: ./foosrefmanagement-ui
      dockerfile: Dockerfile
      args:
        TELEGRAM_BOT_NAME: ${TELEGRAM_BOT_NAME}
    ports:
      - 8080:80
    depends_on:
      - foosrefmanagement
    environment:
      APP_HOST: ${APP_HOST}
    volumes:
      - staticfiles:/usr/src/app/staticfiles
      - media:/usr/src/app/media
volumes:
  staticfiles:
  postgresdata:
  media:
