services:
  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: ${DEFAULT_DATABASE_PASSWORD}
      POSTGRES_USER: ${DEFAULT_DATABASE_USER}
      POSTGRES_DB: ${DEFAULT_DATABASE_NAME}
  adminer:
    image: adminer
    ports:
      - 8080:8080
  foosrefmanagement:
    image: nkuznetsov44/foosrefmanagement
    build:
      context: ./foosrefmanagement
      dockerfile: Dockerfile
    command: gunicorn foosrefmanagement.wsgi:application --bind 0.0.0.0:8000
    depends_on:
      - postgres
    environment:
      DEFAULT_DATABASE_NAME: ${DEFAULT_DATABASE_NAME}
      DEFAULT_DATABASE_USER: ${DEFAULT_DATABASE_USER}
      DEFAULT_DATABASE_PASSWORD: ${DEFAULT_DATABASE_PASSWORD}
      DEFAULT_DATABASE_HOST: postgres
      DEFAULT_DATABASE_PORT: 5432
    volumes:
      - staticfiles:/usr/src/app/staticfiles
  nginx:
    build: ./nginx
    ports:
      - 80:80
    depends_on:
      - foosrefmanagement
    volumes:
      - staticfiles:/usr/src/app/staticfiles
volumes:
  staticfiles: