services:
  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: ${DEFAULT_DATABASE_PASSWORD}
      POSTGRES_USER: ${DEFAULT_DATABASE_USER}
      POSTGRES_DB: ${DEFAULT_DATABASE_NAME}
      COMPOSE_HTTP_TIMEOUT: 300
    ports:
      - 5432:5432
    volumes:
      - postgresdata:/var/lib/postgresql/data
  adminer:
    image: adminer
    ports:
      - ${PG_ADMIN_PORT}:8080
  foosrefmanagement:
    image: nkuznetsov44/foosrefmanagement
    build:
      context: ./foosrefmanagement
      dockerfile: Dockerfile
    command: gunicorn foosrefmanagement.wsgi:application --bind 0.0.0.0:8000
    depends_on:
      - postgres
    environment:
      ENVIRONMENT: ${ENVIRONMENT}
      DEFAULT_DATABASE_NAME: ${DEFAULT_DATABASE_NAME}
      DEFAULT_DATABASE_USER: ${DEFAULT_DATABASE_USER}
      DEFAULT_DATABASE_PASSWORD: ${DEFAULT_DATABASE_PASSWORD}
      DEFAULT_DATABASE_HOST: postgres
      DEFAULT_DATABASE_PORT: 5432
      DJANGO_SUPERUSER_EMAIL: ${DJANGO_SUPERUSER_EMAIL}
      DJANGO_SUPERUSER_USERNAME: ${DJANGO_SUPERUSER_USERNAME}
      DJANGO_SUPERUSER_PASSWORD: ${DJANGO_SUPERUSER_PASSWORD}
    volumes:
      - staticfiles:/usr/src/app/staticfiles
  nginx:
    build:
      context: ./foosrefmanagement-ui
      dockerfile: Dockerfile
    ports:
      - ${WEBAPP_PORT}:80
    depends_on:
      - foosrefmanagement
    volumes:
      - staticfiles:/usr/src/app/staticfiles
volumes:
  staticfiles:
  postgresdata:
