# Generated by Django 4.0.2 on 2022-07-27 12:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app', '0009_delete_telegramuser'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InvitationToken',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('issue_timestamp', models.IntegerField()),
                ('status', models.CharField(choices=[('ISSUED', 'Issued'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='ISSUED', max_length=63)),
                ('issued_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issued_invitation_tokens', to=settings.AUTH_USER_MODEL)),
                ('issued_for_referee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitation_tokens', to='app.referee')),
            ],
        ),
    ]
