# Generated by Django 4.0.2 on 2022-07-26 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_auth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramuser',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
