# Generated by Django 4.0.2 on 2022-02-16 12:01

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Referee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('languages', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('RU', 'Russian'), ('EN', 'English'), ('FR', 'French'), ('GE', 'German')], max_length=2), size=None)),
                ('rank', models.CharField(choices=[('ASSISTANT', 'Assistant'), ('REGIONAL', 'Regional'), ('NATIONAL', 'National'), ('INTERNATIONAL', 'International')], default='ASSISTANT', max_length=63)),
            ],
        ),
        migrations.CreateModel(
            name='RefereedEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('MASTERS', 'Masters'), ('PRO_TOUR', 'Pro Tour'), ('RUSSIAN_CUP_STAGE', 'Russian Cup Stage'), ('RUSSIAN_CUP_FINAL', 'Russian Cup Final'), ('TEAMS', 'Teams')], max_length=63)),
            ],
        ),
        migrations.CreateModel(
            name='RefereedGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_player', models.CharField(max_length=255)),
                ('second_player', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('assistant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assistants', to='app.referee')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.refereedevent')),
                ('referee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='referees', to='app.referee')),
            ],
        ),
    ]
