# Generated by Django 4.0.2 on 2022-02-17 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_referee_email_alter_referee_languages'),
    ]

    operations = [
        migrations.AddField(
            model_name='referee',
            name='first_name_en',
            field=models.CharField(default='default', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='referee',
            name='last_name_en',
            field=models.CharField(default='default', max_length=255),
            preserve_default=False,
        ),
    ]
