# Generated by Django 4.0.2 on 2022-04-23 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_referee_first_name_en_referee_last_name_en'),
    ]

    operations = [
        migrations.AddField(
            model_name='referee',
            name='city',
            field=models.CharField(choices=[('MOSCOW', 'Москва'), ('SAINT_PETERSBURG', 'Санкт-Петербург'), ('KALININGRAD', 'Калининград'), ('TOMSK', 'Томск'), ('KAZAN', 'Казань'), ('YAROSLAVL', 'Ярославль'), ('OTHER', 'Другой')], default='OTHER', max_length=63),
        ),
        migrations.AlterField(
            model_name='refereedevent',
            name='type',
            field=models.CharField(choices=[('MASTERS', 'Masters'), ('PRO_TOUR', 'Pro Tour'), ('RUSSIAN_CUP_STAGE', 'Этап чемпионата России'), ('RUSSIAN_CUP_FINAL', 'Финал чемпионата России'), ('LOCAL_TOURNAMENT', 'Локальный турнир'), ('TEAMS', 'Лига')], max_length=63),
        ),
    ]
