# Generated by Django 4.0.2 on 2022-04-24 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_referee_city_alter_refereedevent_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='referee',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
