# Generated by Django 4.0.2 on 2022-05-05 19:04

import app.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_referee_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='referee',
            name='rank_update',
            field=models.DateField(default=datetime.datetime(1900, 1, 1, 0, 0)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='refereedgame',
            name='category',
            field=models.CharField(choices=[('OS', 'OS'), ('OD', 'OD'), ('WS', 'WS'), ('WD', 'WD'), ('MD', 'MD'), ('AS', 'AS'), ('AD', 'AD'), ('PRO_AM', 'Pro-Am'), ('COD', 'COD'), ('TEAM', 'Team'), ('OTHER', 'Other')], default='OTHER', max_length=31),
        ),
        migrations.AddField(
            model_name='refereedgame',
            name='stage',
            field=models.CharField(choices=[('FINAL', 'Final'), ('SEMI_FINAL', '1/2'), ('QUARTER_FINAL', '1/4'), ('WB_FINAL', 'WB Final'), ('WB_SEMIFINAL', 'WB Semi-Final'), ('LB_FINAL', 'LB Final'), ('LB_4', 'LB [4]'), ('LB_5_6', 'LB [5-6]'), ('OTHER', 'Other')], default='OTHER', max_length=31),
        ),
        migrations.AlterField(
            model_name='referee',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=app.models.referee_profile_photo_path),
        ),
    ]
