# Generated by Django 4.0.2 on 2022-05-06 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_referee_rank_update_refereedgame_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refereedgame',
            name='category',
            field=models.CharField(choices=[('OS', 'OS'), ('OD', 'OD'), ('WS', 'WS'), ('WD', 'WD'), ('MD', 'MD'), ('AS', 'AS'), ('AD', 'AD'), ('ND', 'ND'), ('PRO_AM', 'Pro-Am'), ('COD', 'COD'), ('TEAM', 'Team'), ('OTHER', 'Other')], default='OTHER', max_length=31),
        ),
    ]
