# Generated by Django 4.0.2 on 2022-07-26 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_telegramuser_referee_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TelegramUser',
        ),
    ]
