# Generated by Django 4.0.2 on 2022-07-31 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_delete_telegramuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='referee',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
