name: Publish Docker image

on:
  push

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        
      - name: Build and push foosrefmanagement
        uses: docker/build-push-action@v2
        with:
          context: ./foosrefmanagement
          file: ./foosrefmanagement/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/foosrefmanagement:github-actions
          
      - name: Build and push foosrefmanagement-ui
        uses: docker/build-push-action@v2
        with:
          context: ./foosrefmanagement-ui
          file: ./foosrefmanagement-ui/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/foosrefmanagement-ui:github-actions
